# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

MXX=/usr/bin/clang
CU=/usr/bin/clang++
CC=/usr/bin/gcc
CXX=/usr/bin/gcc
GC=/usr/bin/go
AS=/usr/bin/gcc
MM=/usr/bin/clang

SH=/usr/bin/g++
LD=/usr/bin/g++
GC_LD=/usr/bin/go
AR=/usr/bin/ar
GC_AR=/usr/bin/go

lexical-analyzer_CXXFLAGS=-fvisibility=hidden -O3 -Iinclude -m64 -I/usr/local/include -I/usr/include
lexical-analyzer_LDFLAGS=-s -fvisibility=hidden -m64 -L/usr/local/lib -L/usr/lib

default:  lexical-analyzer

all:  lexical-analyzer

.PHONY: default all  lexical-analyzer

lexical-analyzer: build/linux/x86_64/release/lexical-analyzer
build/linux/x86_64/release/lexical-analyzer: build/.objs/lexical-analyzer/linux/x86_64/release/src/main.cpp.o build/.objs/lexical-analyzer/linux/x86_64/release/src/output.cpp.o build/.objs/lexical-analyzer/linux/x86_64/release/src/lexer.cpp.o
	@echo linking.release lexical-analyzer
	@mkdir -p build/linux/x86_64/release
	@$(LD) -o build/linux/x86_64/release/lexical-analyzer build/.objs/lexical-analyzer/linux/x86_64/release/src/main.cpp.o build/.objs/lexical-analyzer/linux/x86_64/release/src/output.cpp.o build/.objs/lexical-analyzer/linux/x86_64/release/src/lexer.cpp.o $(lexical-analyzer_LDFLAGS) > build/.build.log 2>&1

build/.objs/lexical-analyzer/linux/x86_64/release/src/main.cpp.o: src/main.cpp
	@echo compiling.release src/main.cpp
	@mkdir -p build/.objs/lexical-analyzer/linux/x86_64/release/src
	@$(CXX) -c $(lexical-analyzer_CXXFLAGS) -o build/.objs/lexical-analyzer/linux/x86_64/release/src/main.cpp.o src/main.cpp > build/.build.log 2>&1

build/.objs/lexical-analyzer/linux/x86_64/release/src/output.cpp.o: src/output.cpp
	@echo compiling.release src/output.cpp
	@mkdir -p build/.objs/lexical-analyzer/linux/x86_64/release/src
	@$(CXX) -c $(lexical-analyzer_CXXFLAGS) -o build/.objs/lexical-analyzer/linux/x86_64/release/src/output.cpp.o src/output.cpp > build/.build.log 2>&1

build/.objs/lexical-analyzer/linux/x86_64/release/src/lexer.cpp.o: src/lexer.cpp
	@echo compiling.release src/lexer.cpp
	@mkdir -p build/.objs/lexical-analyzer/linux/x86_64/release/src
	@$(CXX) -c $(lexical-analyzer_CXXFLAGS) -o build/.objs/lexical-analyzer/linux/x86_64/release/src/lexer.cpp.o src/lexer.cpp > build/.build.log 2>&1

clean:  clean_lexical-analyzer

clean_lexical-analyzer: 
	@rm -f build/linux/x86_64/release/lexical-analyzer
	@rm -f build/.objs/lexical-analyzer/linux/x86_64/release/src/main.cpp.o
	@rm -f build/.objs/lexical-analyzer/linux/x86_64/release/src/output.cpp.o

